spring:
  uploadDir: "./images"
  web:
    resources:
      static-locations:
        - classpath:/static/images

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true

  sql:
    init:
      mode: always

  datasource:
    primary:
      jdbc-url: jdbc:h2:file:./data/primary
      username: root
      password: root
      driver-class-name: org.h2.Driver
    secondary:
      jdbc-url: jdbc:h2:file:./data/secondary
      username: root
      password: root
      driver-class-name: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2-console

  application:
    name: F1Hub

  mail:
    host: smtp-relay.brevo.com
    port: 587
    username: 8e3150002@smtp-brevo.com
    password: xsmtpsib-275a1c6345a10ff3add1dfa49958b6f41ea93ea70bc52e7a1e142bfed0137333-QRykgXSavmdsIEH8
    properties:
      mail:
        smtp.starttls.enable: true
        smtp.auth: true

security:
  jwt:
    key: ${KEY}
    expiration-time: ${EXPIRATION_TIME}
